version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: graphene-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: graphene_store_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - graphene-dev-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: graphene-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - graphene-dev-network
    command: redis-server --appendonly yes --requirepass redis123

  # Backend Service (Development)
  backend:
    build:
      context: ./backend
      target: dev
    container_name: graphene-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/graphene_store_dev?authSource=admin
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: dev-jwt-secret-not-for-production
      SESSION_SECRET: dev-session-secret-not-for-production
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      PAYPAL_ENVIRONMENT: sandbox
      LOG_LEVEL: debug
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - graphene-dev-network
    depends_on:
      - mongodb
      - redis

  # Frontend Service (Development)
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: graphene-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:5000
      VITE_PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      VITE_ENVIRONMENT: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - graphene-dev-network
    depends_on:
      - backend

volumes:
  mongodb_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  graphene-dev-network:
    driver: bridge