version: '3.8'

services:
  mongodb-test:
    image: mongo:6.0
    container_name: rdjcustoms-mongodb-test
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rdjcustoms-test
    volumes:
      - mongodb-test-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb-test-data:
    driver: local